<?php

declare(strict_types=1);

namespace Cpdeploy\Laravel;

/**
 * LAR-06: a Laravel APP_KEY for AES-256-CBC, generated by the tool.
 */
final class AppKey
{
    public static function generate(): string
    {
        return 'base64:' . base64_encode(random_bytes(32));
    }

    public static function isSet(?string $value): bool
    {
        return $value !== null && trim($value) !== '';
    }
}
